name: example
description: "A Flutter project to demonstrate the use of the scryfall_api_symbols package."
publish_to: 'none'

version: 1.0.1+1

environment:
  sdk: ^3.8.0

dependencies:
  flutter:
    sdk: flutter
  scryfall_api: ^2.5.0
  scryfall_api_symbols:
    path: ../

dev_dependencies:
  flutter_lints: ^6.0.0
