name: scryfall_api_symbols
description: Enhance the scryfall_api package with the ability to easily display the MTG symbols as Flutter widgets.
repository: https://github.com/zmuranaka/scryfall_api_symbols
issue_tracker: https://github.com/zmuranaka/scryfall_api_symbols/issues
version: 2.0.0

environment:
  sdk: ^3.6.0
  flutter: ">=3.27.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.1.0
  mtg_symbology: ^1.0.0
  scryfall_api: ^2.1.0

dev_dependencies:
  flutter_lints: ^5.0.0
  test: ^1.25.15
